alias ta='tmux attach'
alias tls='tmux ls'
alias tat='tmux attach -t'
alias tns='tmux new-session -s'
alias ts='tmux new-session -d "sleep 1" && tmux source-file ~/.dotfiles/tmux/dev.tmux_setup'
alias ts_spark='tmux new-session -d "sleep 1" && tmux source-file ~/.dotfiles/tmux/dev_spark.tmux_setup'
alias ts_dotfiles='tmux new-session -d "sleep 1" && cd ~/.dotfiles && tmux source-file ~/.dotfiles/tmux/dotfiles.tmux_setup'
